use comp440;

CREATE TABLE IF NOT EXISTS items (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    PRICE DOUBLE NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    TIMES_POSTED DATE NOT NULL
);
